[package]
name = "rustrest-remote"
version = "0.1.0"
edition = "2024"

[lib]
name = "rustrest_remote"

[dependencies]
rustrest-ssh = { path = "../rustrest-ssh" }
rustrest-remote-protocol = { path = "../rustrest-remote-protocol" }
rustrest-terminal = { path = "../rustrest-terminal" }
tokio = { version = "1", features = ["rt", "sync", "macros", "io-util", "process"] }
thiserror = "2.0.20"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "process", "io-util"] }
