[package]
name = "rustrest-core"
version = "0.1.1"
edition = "2024"

[lib]
name = "rustrest_core"

[dependencies]
tokio = { version = "1", features = ["fs", "rt", "sync", "time", "macros"] }
tokio-util = "0.7"
reqwest = { version = "0.12", default-features = false, features = ["multipart", "json", "rustls-tls"] }
boa_engine = "0.21.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.150"
dirs = "5"
