[package]
name = "rustrest-core"
version = "0.1.1"
edition = "2024"

[lib]
name = "rustrest_core"

[dependencies]
tokio = { version = "1", features = ["fs", "rt", "sync", "time", "macros", "net", "io-util", "process"] }
tokio-util = "0.7"
reqwest = { version = "0.12", default-features = false, features = ["multipart", "json", "rustls-tls"] }
boa_engine = "0.21.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.150"
dirs = "7.0.0"
url = "2.5"
http = "1"
bytes = "1"
hyper = { version = "1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"
tokio-rustls = { version = "0.26", default-features = false, features = ["tls12", "ring"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pki-types = "1"
webpki-roots = "1"
